USE [master]
GO
/****** Object:  Database [HotelUltraDB]    Script Date: 2025/02/03 21:39:55 ******/
CREATE DATABASE [HotelUltraDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelUltraDB', FILENAME = N'HotelUltraDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelUltraDB_log', FILENAME = N'HotelUltraDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HotelUltraDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelUltraDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HotelUltraDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HotelUltraDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HotelUltraDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HotelUltraDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HotelUltraDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [HotelUltraDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [HotelUltraDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HotelUltraDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HotelUltraDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HotelUltraDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HotelUltraDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HotelUltraDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HotelUltraDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HotelUltraDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HotelUltraDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [HotelUltraDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HotelUltraDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HotelUltraDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HotelUltraDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HotelUltraDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HotelUltraDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HotelUltraDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HotelUltraDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HotelUltraDB] SET  MULTI_USER 
GO
ALTER DATABASE [HotelUltraDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HotelUltraDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HotelUltraDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HotelUltraDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HotelUltraDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HotelUltraDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HotelUltraDB] SET QUERY_STORE = OFF
GO
USE [HotelUltraDB]
GO
/****** Object:  Table [dbo].[Hotel]    Script Date: 2025/02/03 21:39:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hotel](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelName] [nvarchar](255) NOT NULL,
	[Location] [nvarchar](255) NOT NULL,
	[Enabled] [bit] NULL,
	[CreationDate] [datetime] NULL,
	[Favorite] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LoginUser]    Script Date: 2025/02/03 21:39:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LoginUser](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[DocumentNumber] [nvarchar](50) NOT NULL,
	[Enabled] [bit] NULL,
	[CreationDate] [datetime] NULL,
	[UserName] [nchar](50) NULL,
	[Password] [nchar](50) NULL,
	[UserType] [nchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[DocumentNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservation]    Script Date: 2025/02/03 21:39:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TravelerId] [int] NOT NULL,
	[HotelId] [int] NOT NULL,
	[RoomId] [int] NOT NULL,
	[AgentId] [int] NOT NULL,
	[CheckInDate] [date] NOT NULL,
	[CheckOutDate] [date] NOT NULL,
	[TotalGuests] [int] NOT NULL,
	[TotalPrice] [decimal](10, 2) NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[CreationDate] [datetime] NULL,
	[Enabled] [bit] NULL,
	[FullNameEmergency] [nchar](50) NULL,
	[PhoneEmergency] [nchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Room]    Script Date: 2025/02/03 21:39:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[HotelId] [int] NOT NULL,
	[RoomType] [nvarchar](100) NOT NULL,
	[BaseCost] [decimal](10, 2) NOT NULL,
	[Taxes] [decimal](10, 2) NOT NULL,
	[Location] [nvarchar](255) NULL,
	[Enabled] [bit] NULL,
	[CreationDate] [datetime] NULL,
	[MaxGuest] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Traveler]    Script Date: 2025/02/03 21:39:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Traveler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[BirthDate] [date] NOT NULL,
	[Gender] [nvarchar](50) NOT NULL,
	[DocumentType] [nvarchar](50) NOT NULL,
	[DocumentNumber] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[Phone] [nvarchar](50) NULL,
	[CreationDate] [datetime] NULL,
	[IdServiceOwner] [nchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[DocumentNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Room] ADD  DEFAULT ((1)) FOR [Enabled]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([HotelId])
REFERENCES [dbo].[Hotel] ([Id])
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([RoomId])
REFERENCES [dbo].[Room] ([Id])
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD FOREIGN KEY([TravelerId])
REFERENCES [dbo].[Traveler] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [FK_Reservation_User] FOREIGN KEY([AgentId])
REFERENCES [dbo].[LoginUser] ([Id])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_User]
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD FOREIGN KEY([HotelId])
REFERENCES [dbo].[Hotel] ([Id])
GO
USE [master]
GO
ALTER DATABASE [HotelUltraDB] SET  READ_WRITE 
GO
